 version: '3'
 services:

   db:
     image: mysql
     container_name: mysite-db
     restart: always
     healthcheck:
       test: "mysql -uhello -p12345 -e 'select 1;'"
       interval: 1s
       retries: 20
     volumes:
       #- ./dbdata:/var/lib/mysql
       - ./dbdata1:/var/lib/mysql
       - ./db.sql:/docker-entrypoint-initdb.d/db.sql
     ports:
       - "3307:3306"
     environment:
       - MYSQL_ROOT_PASSWORD=12345
       - MYSQL_DATABASE_NAME=weather
       - MYSQL_USER=hello

   web:
     build: .
     image: chillthrower/weather-app:latest
     volumes:
       - .:/app
     ports:
       - "8000:8000"
     environment:
       - HOST=db
       - PORT=3306
       - MYSQL_DATABASE_NAME=weather
       - MYSQL_USER=hello
       - MYSQL_ROOT_PASSWORD=12345
     depends_on:
        db:
          condition: service_healthy
     entrypoint: ["/bin/bash", "-c", "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"]